
NAME = megaphone
FLAGS = -Wall -Wextra -Werror
CC = clang++ $(FLAGS)
FILE = megaphone.cpp

all : $(NAME)

$(NAME) :
	@$(CC) $(FILE) -o $(NAME)

clean :

fclean : clean
	@rm -rf $(NAME)

re : fclean all
